### ISSUE TITLE
UnboundLocalError: local variable 's3_url' referenced before assignment

### ISSUE THREAD

**Issue by aveekbu** [eucalyptus/eucalyptus-sosreport-plugins#78]
# sosreport --only-plugins eucafrontend -vv --debug
sosreport (version 2.2)
eucalyptus-sos-plugin (version 0.1.6)
euca-version (both 4.0.0 and 4.0.2) 
[for 4.0.2 its complaining about eucarc file as its throws error for 's3_url']
 
Please enter your first initial and last name [odc-f-29]:
Please enter the case number that you are generating this report for [None]:
 
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 23, in <module>
    sosreport(sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/sos/sosreport.py", line 729, in sosreport
    plug.setup()
UnboundLocalError: local variable 's3_url' referenced before assignment
 
> /usr/lib/python2.6/site-packages/sos/plugins/eucafrontend.py(192)get_s3_url()
-> if s3_url is None:
(Pdb) Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sos/sosreport.py", line 106, in doException
    pdb.pm()
  File "/usr/lib64/python2.6/pdb.py", line 1252, in pm
    post_mortem(sys.last_traceback)
  File "/usr/lib64/python2.6/pdb.py", line 1249, in post_mortem
    p.interaction(None, t)
  File "/usr/lib64/python2.6/pdb.py", line 198, in interaction
    self.cmdloop()
  File "/usr/lib64/python2.6/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
KeyboardInterrupt
 
Original exception was:
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 23, in <module>
    sosreport(sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/sos/sosreport.py", line 729, in sosreport
    plug.setup()
  File "/usr/lib/python2.6/site-packages/sos/plugins/eucafrontend.py", line 691, in setup
    self.eucalyptus_ec2(tmp_dir)
  File "/usr/lib/python2.6/site-packages/sos/plugins/eucafrontend.py", line 617, in eucalyptus_ec2
    self.euca2ools_conf_setup(tmp_dir)
  File "/usr/lib/python2.6/site-packages/sos/plugins/eucafrontend.py", line 363, in euca2ools_conf_setup
    s3_url = self.get_s3_url(tmp_dir)
  File "/usr/lib/python2.6/site-packages/sos/plugins/eucafrontend.py", line 192, in get_s3_url
    if s3_url is None:
UnboundLocalError: local variable 's3_url' referenced before assignment

**Comment by hspencer77** [comment]
Fixed by PR https://github.com/eucalyptus/eucalyptus-sosreport-plugins/pull/80
